### PR TITLE
feat: Add FTX Link

### PR DESCRIPTION
**Pull request by FrancYescO**

### CODE REVIEW

**Comment by ekryski** [comment]
Minor change. Looks good to ship @iamssen @cosullivan 👌

**Comment by cosullivan** [comment]
Hi @FrancYescO ,

Can you please add FTX to the bottom of the Exchanges section. They should appear here in the order in which they have been added. Once that is done I will merge.

Thanks, Cain.

**Comment by FrancYescO** [comment]
Okay i was supposing were in alphabetical order (surely Binance was not the first added 😅)

**Comment by cosullivan** [comment]
@FrancYescO yes, it's only something we've recently decided to standardise on because some other PR's (for liquidations too) have been adjusting the order. So we are just accepting the order as they come in now.

**Comment by FrancYescO** [comment]
here you are :)

**Pull request merged**
